export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_MESSAGE = 'REGISTER_MESSAGE';