export const GROUP_GET_DATA = 'GROUP_GET_DATA';
export const GROUP_POST_DATA = 'GROUP_POST_DATA';
export const GROUP_UPDATE_DATA = 'GROUP_UPDATE_DATA';
export const GROUP_DELETE_DATA = 'GROUP_DELETE_DATA';