export const GROUP_GET_DATA = 'GROUP_GET_DATA';
export const GROUP_POST_DATA = 'GROUP_POST_DATA';
export const GROUP_UPDATE_DATA = 'GROUP_UPDATE_DATA';
export const GROUP_DELETE_DATA = 'GROUP_DELETE_DATA';
export const GROUP_SUCCESS_DATA = 'GROUP_SUCCESS_DATA';
export const GROUP_FAILED_DATA = 'GROUP_FAILED_DATA';