export const SINGLE_CHAT_MEMBER_SUCCESS = 'SINGLE_CHAT_MEMBER_SUCCESS';
export const SINGLE_CHAT_MEMBER_FAILED = 'SINGLE_CHAT_MEMBER_FAILED';
export const SINGLE_CHAT_MEMBER_LOADING = 'SINGLE_CHAT_MEMBER_LOADING';